server:
  port: 8082
spring:
  application:
    name: cloud-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  hystrix:
    enabled: false

